name: Ordinal
version: "1.0.0"
main: org.maboroshi.ordinal.Ordinal
description: Assigns persistent, sequential join IDs (Ordinal ranks) to players with PlaceholderAPI support.
author: Maboroshi
website: https://github.com/MaboroshiKobo/Ordinal
api-version: "1.21"
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false